<%@ Page Language="C#" MasterPageFile="~/InnerMaster.master" AutoEventWireup="true" CodeFile="ViewSubCat.aspx.cs" Inherits="ViewSubCat" Title="Untitled Page" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <table class="style2">
    <tr>
        <td>
            <asp:Label ID="Label1" runat="server" Text="Select Category Name::"></asp:Label>
        </td>
        <td>
            <asp:DropDownList ID="DropDownList1" runat="server" AutoPostBack="True" 
                Height="16px" Width="154px" 
                onselectedindexchanged="DropDownList1_SelectedIndexChanged">
            </asp:DropDownList>
        </td>
    </tr>
    <tr>
        <td colspan="2">
           
            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" 
                        AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
                        onrowcancelingedit="GridView1_RowCancelingEdit" 
                        onrowdeleting="GridView1_RowDeleting" onrowediting="GridView1_RowEditing" 
                        onrowupdating="GridView1_RowUpdating" Width="477px" 
                EnableModelValidation="True" >
                        <Columns >
            
            <asp:TemplateField>
            <ItemTemplate >
            <asp:Label ID="lblcatid" runat ="server" Text ='<%#Eval("SubId") %>' Visible="false" ></asp:Label>
            </ItemTemplate>
            </asp:TemplateField>
            
            <asp:TemplateField HeaderText="Category Name" >
            <ItemTemplate> <%#Eval("SubCatName")%></ItemTemplate> 
            <EditItemTemplate>
            <asp:TextBox ID="txtcategoryName" runat ="server" Text ='<%#Eval("SubCatName") %>'></asp:TextBox>
            </EditItemTemplate>
            </asp:TemplateField>
            
            <%--<asp:TemplateField HeaderText ="SubCategory descr"><ItemTemplate><%#Eval("descr")%> </ItemTemplate>
           <EditItemTemplate >
           <asp:TextBox ID="txtcategoryDesc" runat ="server" Text ='<%#Eval("descr") %>'></asp:TextBox>
           </EditItemTemplate>
            </asp:TemplateField>--%>
            </Columns>
                    </asp:GridView>
        </td>
    </tr>
</table>
</asp:Content>

