<%@ Page Language="C#" AutoEventWireup="true" CodeFile="ViewBooks.aspx.cs" Inherits="ViewBooks" MasterPageFile="~/InnerMaster.master"%>
<asp:Content ID="ViewbookContent" runat="server" ContentPlaceHolderID="ContentPlaceHolder1">
    <table class="style1">
            <tr>
              <td align="right" colspan="2">
                  <asp:HiddenField ID="HiddenField1" runat="server" />
                  <asp:Label ID="Label1" runat="server" Text="Welcome :" Font-Bold="true"></asp:Label>
                  <asp:Label ID="Label2" runat="server"></asp:Label>
              </td>
            </tr>
            <tr>
                <td class="style2" colspan="3" align="center">
                    <asp:Label ID="Label11" runat="server" Text="Book Details" Font-Bold="true"></asp:Label>
            </td>
            </tr>
            <tr>
                <td class="style2" colspan="3" align="center">
                <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" 
                        AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
                        onrowcancelingedit="GridView1_RowCancelingEdit" 
                        onrowdeleting="GridView1_RowDeleting" onrowediting="GridView1_RowEditing" 
                        onrowupdating="GridView1_RowUpdating" Width="426px">
                        <Columns >
                            <asp:TemplateField>
                            <ItemTemplate >
                            <asp:Label ID="lblbookid" runat ="server" Text ='<%#Eval("bookId") %>' Visible="false" ></asp:Label>
                            </ItemTemplate>
                            </asp:TemplateField>
                            
                            <asp:TemplateField HeaderText="Book Name" >
                            <ItemTemplate> <%#Eval("bookname")%></ItemTemplate> 
                            <EditItemTemplate>
                            <asp:TextBox ID="txtbookname" runat ="server" Text ='<%#Eval("bookname") %>'></asp:TextBox>
                            </EditItemTemplate>
                            </asp:TemplateField>
                            
                            <asp:TemplateField HeaderText ="Author"><ItemTemplate><%#Eval("author")%> </ItemTemplate>
                           <EditItemTemplate >
                           <asp:TextBox ID="txtauthor" runat ="server" Text ='<%#Eval("author") %>'></asp:TextBox>
                           </EditItemTemplate>
                            </asp:TemplateField>
                            
                            <asp:TemplateField HeaderText ="Publisher"><ItemTemplate><%#Eval("publisher")%> </ItemTemplate>
                           <EditItemTemplate >
                           <asp:TextBox ID="txtpublisher" runat ="server" Text ='<%#Eval("publisher") %>'></asp:TextBox>
                           </EditItemTemplate>
                            </asp:TemplateField>
                            
                            <asp:TemplateField HeaderText ="No of Copies"><ItemTemplate><%#Eval("noofcopies")%> </ItemTemplate>
                           <EditItemTemplate >
                           <asp:TextBox ID="txtnoofcopies" runat ="server" Text ='<%#Eval("noofcopies") %>'></asp:TextBox>
                           </EditItemTemplate>
                            </asp:TemplateField>
                            
                           
                            
                        </Columns>
                    </asp:GridView>
                </td>
            </tr>
        </table>

</asp:Content>